In [2]:
import torch
import torch.autograd as autograd
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

torch.manual_seed(1)

## Creating Tensors(torch.tensor())

In [3]:
# torch.tensor(data) creates a torch.Tensor object with the given data.
V_data = [1., 2., 3.]
V = torch.tensor(V_data)
print(V)

# Creates a matrix
M_data = [[1., 2., 3.], [4., 5., 6]]
M = torch.tensor(M_data)
print(M)

# Create a 3D tensor of size 2x2x2.
T_data = [[[1., 2.], [3., 4.]],
          [[5., 6.], [7., 8.]]]
T = torch.tensor(T_data)
print(T)

tensor([1., 2., 3.])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])


In [5]:
print(V)

tensor([1., 2., 3.])


In [6]:
print(V[0]) # Scalar (0 dimensional Tensor)

tensor(1.)


In [7]:
print(V[0].item())

1.0


# Reshaping Tensors

In [17]:
x = torch.rand(2,3,4)
print(x)

tensor([[[0.8300, 0.0444, 0.0246, 0.2588],
         [0.9391, 0.4167, 0.7140, 0.2676],
         [0.9906, 0.2885, 0.8750, 0.5059]],

        [[0.2366, 0.7570, 0.2346, 0.6471],
         [0.3556, 0.4452, 0.0193, 0.2616],
         [0.7713, 0.3785, 0.9980, 0.9008]]])


In [20]:
print(x.view(2,12)) # 2 rows,12 columns

tensor([[0.8300, 0.0444, 0.0246, 0.2588, 0.9391, 0.4167, 0.7140, 0.2676, 0.9906,
         0.2885, 0.8750, 0.5059],
        [0.2366, 0.7570, 0.2346, 0.6471, 0.3556, 0.4452, 0.0193, 0.2616, 0.7713,
         0.3785, 0.9980, 0.9008]])


In [12]:
y = x.view(2,-1)
print(y)

tensor([[0.0293, 0.7999, 0.3971, 0.7544, 0.5695, 0.4388, 0.6387, 0.5247, 0.6826,
         0.3051, 0.4635, 0.4550],
        [0.5725, 0.4980, 0.9371, 0.6556, 0.3138, 0.1980, 0.4162, 0.2843, 0.3398,
         0.5239, 0.7981, 0.7718]])


In [13]:
y.shape

torch.Size([2, 12])

In [14]:
z = torch.rand(2,2)
print(z)

tensor([[0.0112, 0.8100],
        [0.6397, 0.9743]])


In [16]:
print(z.view(2,-1).shape) # -1 any shape or max shape that tensor can be created

torch.Size([2, 2])


### Computation Graphs and Automatic Differentitation

In [21]:
x = torch.rand(2,2)
y = torch.rand(2,2)
print(x.requires_grad,y.requires_grad)

False False


In [22]:
z = x+y
print(z.grad_fn)

None


In [23]:
x = x.requires_grad_()
y = y.requires_grad_()
z = x+y
print(z.grad_fn)

In [24]:
# Now z has the computation history that relates itself to x and y
# Can we just take its values, and **detach** it from its history?

new_z = z.detach()

In [27]:
print(new_z.requires_grad)

False


In [28]:
print(new_z.grad_fn)

None


In [30]:
print(x.requires_grad)
print((x**2).requires_grad)

True
True


In [31]:
with torch.no_grad():
    print((x**2).requires_grad)

False
