In [1]:
import torch

In [2]:
torch.ones((2,2))

tensor([[1., 1.],
        [1., 1.]])

In [3]:
torch.rand(2,2)

tensor([[0.8409, 0.1283],
        [0.7064, 0.3046]])

In [9]:
torch.empty(2,2)

tensor([[0., 0.],
        [0., 0.]])

# Seeds
We need seeds to enable reproduction of experimental results. This becomes critical later on where you can easily let people reproduce your code's output exactly as you've produced.

In [4]:
torch.manual_seed(0)
torch.rand(2,2)

tensor([[0.4963, 0.7682],
        [0.0885, 0.1320]])

In [5]:
# Repear creating a PyTorch fixed seed tensor

torch.manual_seed(0)
torch.rand(2,2)

tensor([[0.4963, 0.7682],
        [0.0885, 0.1320]])

In [6]:
torch.rand(2,2)

tensor([[0.3074, 0.6341],
        [0.4901, 0.8964]])

In [7]:
torch.rand(2,2)

tensor([[0.4556, 0.6323],
        [0.3489, 0.4017]])

# Seed for GPU

In [8]:
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(0)

# NumPy and Torch Bridge

In [12]:
import numpy as np

np_array = np.ones((2,2))
print(np_array)
print(type(np_array))

[[1. 1.]
 [1. 1.]]
<class 'numpy.ndarray'>


In [14]:
torch_tensor = torch.from_numpy(np_array)
print(torch_tensor)
print(type(torch_tensor))

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)
<class 'torch.Tensor'>


## Create PyTorch tensor from a different numpy datatype

In [15]:
# Data types matter: intentional error
np_array_new = np.ones((2, 2), dtype=np.int8)
torch.from_numpy(np_array_new)

tensor([[1, 1],
        [1, 1]], dtype=torch.int8)

In [16]:
np_array_new = np.ones((2,2),dtype=np.int64)
torch.from_numpy(np_array_new) # PyTorch long Tensor

tensor([[1, 1],
        [1, 1]])

In [17]:
np_array_new = np.ones((2,2),dtype=np.int32)
torch.from_numpy(np_array_new)# int tensor

tensor([[1, 1],
        [1, 1]], dtype=torch.int32)

In [18]:
np_array_new = np.ones((2,2),dtype=np.uint8)
torch.from_numpy(np_array_new)# byte tensor

tensor([[1, 1],
        [1, 1]], dtype=torch.uint8)

In [20]:
np_array_new = np.ones((2,2),dtype=np.float64)
torch.from_numpy(np_array_new)

#or

np_array_new = np.ones((2,2),dtype=np.double)
torch.from_numpy(np_array_new)

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)

NumPy Array Type	Torch Tensor Type
int64               LongTensor
int32	            IntegerTensor
uint8	            ByteTensor
float64         	DoubleTensor
float32	            FloatTensor
double	            DoubleTensor

# Torch to numpy

In [23]:
torch_tensor = torch.ones(2,2)
type(torch_tensor)
print(torch_tensor)

tensor([[1., 1.],
        [1., 1.]])


In [25]:
torch_to_numpy = torch_tensor.numpy()
type(torch_to_numpy)

numpy.ndarray

# Tensor Operations

In [26]:
a = torch.ones(2,2)
print(a)

tensor([[1., 1.],
        [1., 1.]])


In [27]:
print(a.size())

torch.Size([2, 2])


In [28]:
a.view(4)

tensor([1., 1., 1., 1.])

In [29]:
a.view(4).size()

torch.Size([4])

## Element Wise Addition,Sub,Mul,Div

In [32]:
a = torch.ones(2,2)
print(a)

tensor([[1., 1.],
        [1., 1.]])


In [34]:
b = torch.ones(2,2)
print(b)

tensor([[1., 1.],
        [1., 1.]])


In [36]:
c = a+b
print(c)

tensor([[2., 2.],
        [2., 2.]])


In [38]:
c = torch.add(a,b)
print(c)

tensor([[2., 2.],
        [2., 2.]])


## Tensor Mean

In [39]:
a = torch.Tensor([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
a.size()

torch.Size([10])

In [40]:
a.mean(dim=0)

tensor(5.5000)

In [41]:
a.mean(dim=1)

IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

In [42]:
a = torch.Tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]])

In [43]:
a.size()

torch.Size([2, 10])

In [44]:
a.mean(dim=0)

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [45]:
a.mean(dim=1)

tensor([5.5000, 5.5000])

In [46]:
a = torch.Tensor([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
a.std(dim=0)

tensor(3.0277)