### References: 
1 . https://towardsdatascience.com/pytorch-autograd-understanding-the-heart-of-pytorchs-magic-2686cd94ec95

### Gradients with Pytorch

In [2]:
import torch

In [3]:
a = torch.ones((2,2),requires_grad=True)

In [4]:
a.requires_grad

True

In [5]:
no_gradient = torch.ones(2,2)

In [6]:
no_gradient.requires_grad

False

In [7]:
## Addition

In [8]:
# Behaves similarly to tensors
b = torch.ones((2, 2), requires_grad=True)
print(a + b)
print(torch.add(a, b))

tensor([[2., 2.],
        [2., 2.]], grad_fn=<AddBackward0>)
tensor([[2., 2.],
        [2., 2.]], grad_fn=<AddBackward0>)


In [9]:
print(a * b)
print(torch.mul(a, b))

tensor([[1., 1.],
        [1., 1.]], grad_fn=<MulBackward0>)
tensor([[1., 1.],
        [1., 1.]], grad_fn=<MulBackward0>)
